development:
  adapter: postgresql
  encoding: unicode
  database: store_development
  pool: 5
  username: vidishagoel1989@gmail.com	
  password:VIDISHAGOEL

test:
  adapter: postgresql
  encoding: unicode
  database: store_test
  pool: 5
  username: vidishagoel1989@gmail.com	
  password:VIDISHAGOEL